"""Глобальные константы проекта."""
PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6
USER_FIRST_NAME_MAX_LENGTH = 150
USER_LAST_NAME_MAX_LENGTH = 150
USER_EMAIL_MAX_LENGTH = 254
USER_PHONE_MAX_LENGTH = 15
USER_GITHUB_URL_MAX_LENGTH = 200
